In [13]:
from loading_dataset import load_data
import SimpleITK as sitk
import numpy as np

In [14]:
gt_box_mode = 'cccwhd'
# gt_box_mode = 'xyzxyz'
batch_size = 1
patch_size = [96,96,40]
amp=True
data_list_file_path = '/data/output/msd_train_val3.json'
data_base_dir = '/data/MSD_Images_resample/'

In [15]:
train_loader, val_loader, len_train_ds = load_data(
    gt_box_mode, patch_size, batch_size, amp, data_list_file_path, data_base_dir
)

In [16]:
for val_data in val_loader:
    print(val_data[0]["box"])
    print(val_data[0]["image_meta_dict"]["filename_or_obj"])

metatensor([[438., 334., 105., 462., 353., 115.]], dtype=torch.float16)
/data/MSD_Images_resample/lung_083/lung_083.nii.gz
metatensor([[477., 188., 153., 500., 216., 172.]], dtype=torch.float16)
/data/MSD_Images_resample/lung_079/lung_079.nii.gz


In [5]:
def generate_conversions_info(
    origin, spacing, world_coord, world_dist
):
    print(origin)
    print(spacing)
    print("first conversion, centers world to voxel")
    voxel_coord = np.abs(world_coord - origin) / spacing
    print(world_coord)
    print(voxel_coord)
    voxel_dist = world_dist/ spacing
    print("converting distances")
    print(world_dist)
    print(voxel_dist)

In [6]:
origin = np.array([202.97944641, 227.27944946, -278])
spacing = np.array([0.703125, 0.703125, 1.25])
world_coord = np.array([109.11225891000001,  15.990386959999995, -468.625])
world_dist = np.array([23.203125, 23.203125, 18.75])

In [7]:
generate_conversions_info(origin, spacing, world_coord, world_dist)

[ 202.97944641  227.27944946 -278.        ]
[0.703125 0.703125 1.25    ]
first conversion, centers world to voxel
[ 109.11225891   15.99038696 -468.625     ]
[133.5 300.5 152.5]
converting distances
[23.203125 23.203125 18.75    ]
[33. 33. 15.]


In [8]:
int('aa')

ValueError: invalid literal for int() with base 10: 'aa'

### voxel

In [9]:
voxel_coordinates = np.array([133.5, 300.5, -152.5])
world_coordinates = ((voxel_coordinates * spacing) - origin) * -1
world_coordinates

array([109.11225891,  15.99038696, -87.375     ])

In [10]:
voxel_coordinates = np.array([25.875, 25.875, 14.5625])
world_coordinates = voxel_coordinates * spacing
world_coordinates

array([18.19335938, 18.19335938, 18.203125  ])

In [11]:
world_coord_cent = np.array([133.5, 300.5, 152.5])

In [12]:
world_coord_cent[2] = world_coord_cent[2] * -1
world_coord_cent

array([ 133.5,  300.5, -152.5])