In [17]:
from loading_dataset import load_data
import SimpleITK as sitk
import numpy as np

In [2]:
gt_box_mode = 'cccwhd'
# gt_box_mode = 'xyzxyz'
batch_size = 1
patch_size = [96,96,40]
amp=True
data_list_file_path = '/data/output/LUNA16-micro.json'
data_base_dir = '/data/LUNA16_Images_resample/'

In [3]:
train_loader, val_loader, len_train_ds = load_data(
    gt_box_mode, patch_size, batch_size, amp, data_list_file_path, data_base_dir
)

monai.transforms.io.dictionary LoadImaged.__init__:image_only: Current default value of argument `image_only=False` has been deprecated since version 1.1. It will be changed to `image_only=True` in version 1.3.


In [8]:
for val_data in val_loader:
    print(val_data[0]["box"])
    print(val_data[0]["image_meta_dict"]["filename_or_obj"])

metatensor([[136.0000, 191.6250,  70.5625, 161.8750, 217.5000,  85.1250],
        [255.0000, 240.7500, 172.3750, 269.7500, 255.5000, 180.6250],
        [202.8750, 355.7500, 177.0000, 214.7500, 367.5000, 183.6250],
        [175.0000, 153.1250, 169.7500, 220.8750, 199.0000, 195.5000],
        [128.6250, 310.7500, 135.8750, 135.6250, 317.7500, 139.8750]],
       dtype=torch.float16)
/data/LUNA16_Images_resample/1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886/1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886.nii.gz


[102.2377292, 65.32842988, -240.6955559, 18.210145, 18.210145, 18.210145], <br>
[22.53616818, 34.72145001, -117.4375995, 10.33971307,
                         10.33971307,
                         10.33971307
                    ], <br>
                    [
                         60.18947724,
                         -45.04675978,
                         -112.6427797,
                         8.349225392,
                         8.349225392,
                         8.349225392
                    ], <br>
                    [
                         67.82725575,
                         85.37992457,
                         -109.7467238,
                         32.27003025,
                         32.27003025,
                         32.27003025
                    ], <br>
                    [
                         114.1058249,
                         -11.85681073,
                         -165.6215278,
                         4.915612527,
                         4.915612527,
                         4.915612527
                    ]
               ], <br>
               "image": "1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886/1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886.nii.gz"}

In [ ]:
cccwhd

xyzxyz

In [57]:
print(
    np.absolute(136.0000 - 161.8750),
    np.absolute(191.6250 - 217.5000), 
    np.absolute(70.5625 - 85.1250))
print(
    136.0000 + np.absolute(136.0000 - 161.8750)/2,
    191.6250 + np.absolute(191.6250 - 217.5000)/2,
    70.5625 + np.absolute(70.5625 - 85.1250)/2
)

25.875 25.875 14.5625
148.9375 204.5625 77.84375


In [20]:
def load_itk(filename):
    itkimage = sitk.ReadImage(filename)
    image_array = sitk.GetArrayFromImage(itkimage)
    origin = np.array(list(itkimage.GetOrigin()))
    spacing = np.array(list(itkimage.GetSpacing()))

    return origin, spacing

In [21]:
origin, spacing = load_itk(
    '/data/LUNA16_Images_resample/1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886/1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886.nii.gz'
)
print(origin, spacing)

[ 206.97944641  209.17944336 -338.        ] [0.703125 0.703125 1.25    ]


In [38]:
world_coordinates = np.array([102.2377292, 65.32842988, -240.6955559])
voxel_coordinates = np.absolute(world_coordinates - origin) / spacing
voxel_coordinates

array([148.96599781, 204.58810806,  77.84355528])

In [55]:
world_coordinates = np.array([18.210145, 18.210145, 18.210145])
# voxel_coordinates = np.absolute(world_coordinates - origin) / spacing
voxel_coordinates = world_coordinates/ spacing
voxel_coordinates

array([25.89887289, 25.89887289, 14.568116  ])

In [53]:
voxel_coordinates = np.array([148.9375, 204.5625, 77.84375])
world_coordinates = ((voxel_coordinates * spacing) - origin) * -1
world_coordinates

array([ 102.25776672,   65.34643555, -435.3046875 ])

In [61]:
voxel_coordinates = np.array([25.875, 25.875, 14.5625])
# world_coordinates = ((voxel_coordinates * spacing) - origin) * -1
world_coordinates = voxel_coordinates * spacing
world_coordinates

array([18.19335938, 18.19335938, 18.203125  ])