In [1]:
import torch
from monai.data.box_utils import non_max_suppression

In [8]:
boxes = torch.ones(10,6)
scores = torch.ones(10)
keep = non_max_suppression(boxes, scores, nms_thresh=0.1, max_proposals=2)
boxes_after_nms = boxes[keep]

In [9]:
print(boxes)
print(len(boxes))
print(scores)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
10
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [19]:
print(boxes[0])

tensor([1., 1., 1., 1., 1., 1.])


In [11]:
print(len(boxes_after_nms))
print(keep)

2
tensor([0, 1])


In [12]:
print(type(boxes))

<class 'torch.Tensor'>


In [13]:
# converting to standard mode

In [22]:
pred_boxes = [{'voxel_min': [69, 273, 53], 'voxel_max': [92, 297, 67]}, {'voxel_min': [359, 124, 118], 'voxel_max': [372, 138, 126]}]

converted = []
for a in pred_boxes:
    converted.append([a['voxel_min'][0], a['voxel_min'][1], a['voxel_min'][2], a['voxel_max'][0], a['voxel_max'][1], a['voxel_max'][2]])

print(torch.tensor(converted))


tensor([[ 69, 273,  53,  92, 297,  67],
        [359, 124, 118, 372, 138, 126]])


In [25]:
a = [62, 74, 73, 72, 71, 70, 69, 68, 67, 66]

print(a[[2, 3, 4]])

tensor([73, 72, 71])


In [29]:
x = [1, 2, 3]
x.extend([4, 5])
x.extend([6, 7])
x


[1, 2, 3, 4, 5, 6, 7]